kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-kafka
  namespace: base
  labels:
    app: my-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kafka
  template:
    metadata:
      labels:
        app: my-kafka
    spec:
      hostname: my-kafka
      dnsPolicy: ClusterFirst
      containers:
      - name: my-kafka
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'my-zk.base:2181'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'PLAINTEXT://10.68.180.39:30002'
        - name: KAFKA_LISTENERS
          value: 'PLAINTEXT://0.0.0.0:9092'
        - name: KAFKA_BROKER_ID
	  value: '1'
