apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: redis
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        #- name: POSTGRES_DB
        #  value: "gitlab_production"
        #- name: POSTGRES_USER
        #  value: "gitlab"
        - name: POSTGRES_PASSWORD 
          value: "12345678"
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-project-pvc
