---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-project-pv
  namespace: redis
  labels:
    pv: redis-project-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 119.27.166.193
    path: /nfs_test

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-project-pvc
  namespace: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: redis-project-pv
