apiVersion: v1
kind: Service
metadata:
  labels:
    app: kodexplorer
  name: kodexplorer-server
  namespace: base
spec:
  ports:
  - name: kodexplorer
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30055
  selector:
    app: kodexplorer
  type: NodePort
