apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: base
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: r6by/php7:0.1.1
        name: php
        ports:
        - containerPort: 9000
