apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: base
  labels:
    app: dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
      - image: jpillora/dnsmasq
        name: dnsmasq
        ports:
        - containerPort: 8080
        - containerPort: 53
        volumeMounts:
        - name: conf
          mountPath: /etc/dnsmasq.conf
	  subPath: dnsmasq.conf
      volumes:
      - hostPath:
      	  path: /opt/conf
        name: conf
