kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.yaml: |-
    ping: ""                 
    serversTransport:
      insecureSkipVerify: true 
    api:
      insecure: true          
      dashboard: true        
      debug: false          
    metrics:
      prometheus: ""       
    entryPoints:
      web:
        address: ":80"    
      websecure:
        address: ":443"  
    providers:
      kubernetesCRD: "" 
      kubernetesIngress: ""
    log:
      filePath: ""        
      level: error       
      format: json      
    accessLog:
      filePath: ""     
      format: json    
      bufferingSize: 
      filters:
        #statusCodes: ["200"]
        retryAttempts: true 
        minDuration: 20    
      fields:             
        defaultMode: keep
        names:          
          ClientUsername: drop  
        headers:       
          defaultMode: keep
          names:          
            User-Agent: redact
            Authorization: drop
            Content-Type: keep
